const RANDOM_ITEM = 'RANDOM_ITEM'
const SET_ITEM = 'SET_ITEM'
const SET_CLICKABLE = 'SET_CLICKABLE'
const SET_CHOOSE_INDEX = 'SET_CHOOSE_INDEX'
const SET_DISPLAY = 'SET_DISPLAY'

export const types = {
  RANDOM_ITEM,
  SET_ITEM,
  SET_CLICKABLE,
  SET_CHOOSE_INDEX,
  SET_DISPLAY,
}
